# Generated by Django 4.2.6 on 2023-10-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paleta',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
