# Generated by Django 4.2.6 on 2023-10-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_paleta_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='Paleta',
        ),
    ]
