# Generated by Django 4.2.6 on 2023-11-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_vehiculo_delete_paleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='description',
            field=models.TextField(),
        ),
    ]
