# Generated by Django 4.2.6 on 2023-11-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_vehiculo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
