# Generated by Django 4.2.6 on 2023-11-01 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('vehiculo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehiculo.vehiculo')),
                ('numero_puertas', models.IntegerField()),
            ],
            bases=('vehiculo.vehiculo',),
        ),
        migrations.CreateModel(
            name='Camioneta',
            fields=[
                ('vehiculo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehiculo.vehiculo')),
                ('capacidad_carga', models.FloatField()),
            ],
            bases=('vehiculo.vehiculo',),
        ),
    ]
