# Generated by Django 4.2.6 on 2023-11-01 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_auto_camioneta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auto',
            new_name='SUVs',
        ),
    ]
