# Generated by Django 4.2.6 on 2023-11-19 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_rename_auto_suvs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('vehiculo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehiculo.vehiculo')),
                ('numero_puertas', models.IntegerField()),
            ],
            bases=('vehiculo.vehiculo',),
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='marca',
            new_name='tipo',
        ),
    ]
