# Generated by Django 4.2.6 on 2023-12-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_auto_rename_marca_vehiculo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
